# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.hostname = "web"
    web.vm.box = "gutehall/ubuntu24-04"
    web.vm.box_version = "2024.08.30"
    web.vm.disk :disk, size: "40GB", primary: true

    web.vm.network:private_network, ip: "192.168.20.20"
    web.vm.network:forwarded_port, guest: 80, host: 8000, auto_correct: true
    web.vm.usable_port_range = (8000..9000)
    
    web.vm.synced_folder "./utility", "/home/harrison/utility"

    web.vm.network "public_network"

    web.vm.provider "vmware_desktop" do |vm|
      vm.memory = "2048"
      vm.cpus = 2
    end

    web.vm.provision :shell, path: "./provision.sh"
  end


  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.box = "gutehall/ubuntu24-04"
    db.vm.box_version = "2024.08.30"

    db.vm.network:private_network, ip: "192.168.20.21"
    db.vm.network:forwarded_port, guest: 80, host: 8001, auto_correct: true
    db.vm.usable_port_range = (8000..9000)
    
    db.vm.synced_folder "./utility", "/home/harrison/utility"

    db.vm.network "public_network"

    db.vm.provider "vmware_desktop" do |vm|
      vm.memory = "2048"
      vm.cpus = 2
    end
    config.vm.provision "shell", inline: <<-SHELL
      apt-get install -y wget unzip mysql-server
      systemctl start mysql
      systemctl enable mysql
    SHELL
  end

end
